---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SilverCorridors.
--- DateTime: 2023/9/9 16:12
---
local key = KEYS[1]; -- 锁的key
local threadId = ARGV[1]; -- 线程标识
local releaseTime = ARGV[2]; -- 释放时间

if  (redis.call('exist', key) == 0) then
    -- 锁不存在，新建 key
    redis.call('hset', key, threadId, '1');
    -- 设置有效期
    redis.call('expire', key, releaseTime);
end

-- 锁已经存在，看看线程标识是否是自己
if (redis.call('exist', key, threadId) == 1) then
    redis.call('hincrby', key, threadId, '1');
    redis.call('expire', key, releaseTime);
    return 1;
end

return 0; -- 走到这里说明获取的锁不是自己, 获取锁失败

