---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by silverCorridors.
--- DateTime: 2023/9/10 17:57
---
--- 参数：优惠券id 、 用户id
local voucherId = ARGV[1];
local userId = ARGV[2];
local orderId = ARGV[3];

-- 数据key
-- 库存key
local stockKey = 'seckill:stock:' .. voucherId;
-- 订单key
local orderKey = 'seckill:order:' .. voucherId;
-- 判断库存是否充足, 不充足返回1
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1;
end
-- 判断用户是否下单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 存在，说明是重复下单
    return 2;
end
-- 扣库存
redis.call('incrby', stockKey, -1);
-- 下单（保存用户id）
redis.call('sadd', orderKey, userId);
-- 发送消息到消息队列
redis.call('XADD', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0;