---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SilverCorridors.
--- DateTime: 2023/9/9 16:23
---

local key = KEYS[1];
local threadId = ARGV[1];
local releaseTime = ARGV[2];
-- 判断锁是否是被自己拥有
if (redis.call('HEXISTS', key, threadId) == 0) then
    return nil; -- 如果已经不是自己，直接返回
end
-- 是自己的锁, 重入
local count = redis.call('HINCRBY', key, threadId, -1);
-- 判断是否重入次数已经为0
if (count > 0) then
    -- 大于零说明不能释放锁，重置有效期，直接返回
    redis.call('expire', key, releaseTime);
    return nil;
else
    -- 否则，释放锁
    redis.call('HDEL', key, threadId);
    return nil;
end